### ISSUE TITLE
Vanguard Shield Specialist

### ISSUE THREAD

**Issue by bighurt23** [aevitas/BuddyWing.DefaultCombat#1]
Routine does not work 

2015-11-23 21:15:36,759 [1] INFO Log - Medpac Created!
2015-11-23 21:15:39,114 [7] INFO Log - User is a Trooper
2015-11-23 21:15:40,186 [7] INFO Log - Advanced Class: Vanguard / Discipline: CanNotBeDetermined <--------
2015-11-23 21:15:40,187 [7] INFO Log - Routine Path: Routines

**Comment by aevitas** [comment]
Thanks, either @alltrueist or myself will look at it.

**Comment by bighurt23** [comment]
Also, I did the dirty fix and it does work but does not switch between targets or continue after switching targets doing damage. Does damage to one mob person then stops.

**Comment by aevitas** [comment]
This issue is also included in #2 and is most likely resolved via a change in BW's core.

**Comment by aevitas** [comment]
@bighurt23 Can you please confirm this is either fixed or still an issue with 1.0.1256.821? Thanks!

**Comment by Markeeen** [comment]
Tested on Vanguard Shield Specialist and everything seems to be in working order!

**Comment by aevitas** [comment]
Thanks, considering this one resolved then :8ball:
