### ISSUE TITLE
Change on pause button

### ISSUE THREAD

**Issue by cassrgs** [aevitas/BuddyWing.DefaultCombat#13]
Hello there

It would be awesome for people that use BW as lazyraider a way to use pause as push/release button as a way to use situational cooldowns that need to be used on specific moments.

For example i have a stun on shift+r. When i press shift the rotation pauses when i release it continues

**Comment by aevitas** [comment]
Can be done but requires some work in BW's core.

**Comment by cassrgs** [comment]
so the current pause function its on combathotkeys.cs and the pause its Hotkeys.RegisterHotkey

Cant add another function on this file like pause2 with a keydown event?

**Comment by cassrgs** [comment]
made a plugin with this functionality so i guess we may close this
