### ISSUE TITLE
Deception Assassin being read as Sorceror Madness

### ISSUE THREAD

**Issue by CryoGenesisX** [aevitas/BuddyWing.DefaultCombat#19]
Something is off with the detection of Deception Assassin.
Its being read as Sorceror Madness.
`[DefaultCombat] Class: Inquisitor
 [DefaultCombat] Advanced Class: Assassin
 [DefaultCombat] Discipline: Madness
 [DefaultCombat] [Hot Key][F7] Toggle AOE
 [DefaultCombat] [Hot Key][F8] Load UI
 [DefaultCombat] [Hot Key][F12] Set Tank
 [DefaultCombat] Rotation Selected : Sorcerer Madness`

**Comment by lonestr9** [comment]
I think this is fixed now.  Has been working for the last couple updates; working on Build 888

**Comment by lonestr9** [comment]
This issue has been resolved since Build 888

**Comment by aevitas** [comment]
Sweet, marking this as closed then.
