### ISSUE TITLE
Add harvesting from corpses

### ISSUE THREAD

**Issue by trasser** [aevitas/BuddyWing.DefaultCombat#25]
Atm we have plugin [https://www.thebuddyforum.com/buddy-wing-forum/buddy-wing-plugins/241185-plugin-proximityinteract-npcs.html](url)

But routine dont know about harvesting. And run to next target after [Poi.Clear] Reason: Done Looting.

Accordingly, the plug-in is trying to collect resources on a routine running to the next target. Because of this plugin sometimes manages to gather resources from one or two corpses, and sometimes nothing at all does not have time to collect. And never has time to gather resources from all dead.

Need any opportunity to get the plugin information about what the harvest is over and we can move on. Or embed the collection function in routine

**Comment by aevitas** [comment]
We can't possibly have the core of the bot know what plugins are running and what they're up to. The most elegant solution I think would be using TreeHooks to hook the looting behaviour, and add the harvesting logic that way. It could be added after the bot's regular looting logic works, ensuring the bot takes its time harvesting corpses properly.

On a side note, @Wired203 did quite a bit of work on integrating this into the routine: https://github.com/BosslandGmbH/BuddyWing/issues/16

Once the code's properly reviewed and tested, it may become a part of the routine's functioning.

**Comment by Wired203** [comment]
Trasser feel free to use the Default Combat Test Edition which has all of my code changes,  Under combat routines there's a SVN.  I have sent all of those changes for approval to Default Combat but there's a ton of code for Aevitas to go over as I rewrote a lot to get things to feel right.  Disable your plugin when using the test edition as scavenging/bio are built into that default combat routine.

**Comment by trasser** [comment]
Thx. ill try.

**Comment by Logandros** [comment]
This was implemented with scavenge.cs in defaultcombat
