### ISSUE TITLE
DefaultCombat will not work with 5.0 changes. 

### ISSUE THREAD

**Issue by pjmagee** [aevitas/BuddyWing.DefaultCombat#26]
Many abilities have been changed and moved around in the upcoming 5.0 release. The rotations will mostly stay the same, however the routes will need to be reviewed for each class. 

Some examples: 
- Assassins lose phase walk and their rotation has changed.
- Marauder carnage rotation has changed with a newer ability added into the mix
- Rage rotation has been changed.

[Many other changes....](https://swtor.jedipedia.net/en/news/5-0-class-changes)

**Comment by CryoGenesisX** [comment]
already working on it

**Comment by Logandros** [comment]
I think as of tonight we are golden. Now of course they could probably use optimizations and tweaks but .. that's further down the road
